name: GitHub App access token generator
description: Generates a app installation access token to be used for cloning dependancies from other internal or private repositories using docker and golang
inputs:
  app-private-key:
    description: Private key for the GitHub App
    required: true
  app-id:
    description: GitHub App ID
    required: true
  app-installation-id:
    description: GitHub Installation ID
    required: true
  base-url:
    description: Base URL of the GitHub. If you are using GitHub enterprise, please configure this.
    required: false
    default: api.github.com
outputs:
  token:
    description: Installation access token for the GitHub App
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.app-private-key }}
    - ${{ inputs.app-id }}
    - ${{ inputs.app-installation-id }}
    - ${{ inputs.base-url }}
author: mlioo
branding:
  icon: zap
  color: green
